config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  root to: 'home#index'

  resources :users

  resources :groups do
    resources :entities
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    cannot :read, :all

    return unless user.present?

    can :create, :all
    can :destroy, :all, User_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :group, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_one_attached :icon
  has_many :entities, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy
  has_many :entities, through: :groups, foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @group = Group.find(params[:group_id])
    @entities = current_user.entities
  end

  def new
    @group = Group.find(params[:group_id])
    @entities = @group.entities
  end

  def create
    @group = Group.find(params[:group_id])
    @entity = @group.entities.build(entity_params)
    @entity.user = current_user
    if @entity.save
      flash[:notice] = 'Entity created successfully'
      redirect_to group_entities_path(current_user, @group)
    else
      flash[:alert] = 'Entity not created'
      render :new
    end
  end

  def destroy
    @entity = Entity.find(params[:id])
    @entity.destroy
    flash[:notice] = 'Entity was deleted successfully.'
    redirect_to group_entity_path
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = current_user.groups
  end

  def show
    @group = Group.find(params[:id])
    @entities = @group.entities
  end

  def new
    @group = Group.new
  end

  def create
    @user = current_user
    @group = Group.new(group_params)
    @group.user_id = @user.id
    respond_to do |format|
      format.html do
        if @group.save
          flash[:success] = 'Group saved successfully'
          redirect_to groups_path
        else
          flash[:error] = 'Error: Group could not be saved'
          redirect_to new_group_path(@user)
        end
      end
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:notice] = 'Group updated successfully'
      redirect_to groups_path(current_user.id)
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path(current_user.id)
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_action :authenticate_user!, only: %i[index]
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/entities/_form.html.erb
<section>
  <div>
    <h2>ADD TRANSACTION</h2>
  </div>

  <div>
    <%= form_with model: [@group, @group.entities.build] do |form| %>
      <div class="form-bdy">
        <div>
          <%= form.number_field :user_id, id: :purchase_author_id, value: current_user.id, type: :hidden %>
        </div>

        <div class="mb-3">
          <% form.label :name, style: "display: block" %>
          <%= form.text_field :name, autofocus: true, placeholder: 'Name', class: 'form-control border-top-0 border-end-0 border-start-0' %>
        </div>

        <div class="mb-3">
          <% form.label :amount, style: "display: block" %>
          <%= form.number_field :amount, autofocus: true, placeholder: 'Amount', class: 'form-control border-top-0 border-end-0 border-start-0'  %>
        </div>

        <div class="mb-3">
          <%= form.label :group_id, "Group ID" %>
          <%= form.collection_select :group_id, current_user.groups, :id, :name, prompt: true %>
        </div>

        <div>
          <%= form.submit value: 'Submit', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/entities/index.html.erb
<%= render 'partials/newnavgrp' %>

<section class="ent-con d-flex flex-column align-items-center">
  <div>
    <h5 class="text-center mt-4">Total spend for <%= @group.name %> : $<%= @group.entities.sum(:amount) %></h5>
  </div>
  
  <div>
    <table class="table table-striped", style="text-align: center;">
      <thead>
        <tr>
          <th>Date</th>
          <th>Name</th>
          <th>Amount</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% if @group.entities.empty? %>
          <h3>No records found!</h3>
        <% else %>
          <% @group.entities.each do |t| %>
            <tr>
            <td><%= t.created_at.strftime("%d-%b-%Y") %></td>
            <td><%= t.name %></td>
            <td>$<%= t.amount %></td>
            <td>        
                <%= button_to "Delete", group_entity_path(current_user, t.group, t ), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-success mb-5" %>
            </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="grp-add">
    <%= link_to "ADD TRANSACTION", new_group_entity_path, class:"grp-add-btn" %>
  </div>
</section>

app/views/entities/new.html.erb
<%= render 'partials/newent' %>

<section class="new-grp d-flex justify-content-center">
<%= render "form", entity: @entity %>
</section>

app/views/groups/_form.html.erb
<section>
  <div>
    <h2>ADD CATEGORY</h2>
  </div>

  <div>
    <%= form_with(model: group) do |form| %>
      <div class="form-grp d-flex flex-column">
        <div >
          <%= form.number_field :author_id, id: :group_author_id, value: current_user.id, type: :hidden %>
        </div>

        <div>
          <% form.label :name, style: "display: block" %>
          <%= form.text_field :name, autofocus: true, placeholder: 'Name', class: "form-control border-top-0 border-end-0 border-start-0" %>
        </div>

        <div>
          <% form.label :icon, style: "display: block" %>
          <%= form.file_field :icon, class: 'btn btn-outline-light p-0'%>
        </div>

        <div>
          <%= form.submit value: 'Submit', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/groups/edit.html.erb
<h1>Edit Group</h1>

app/views/groups/index.html.erb
<%= render 'partials/navgrp' %>

<section class="grp-con d-flex flex-column align-items-center justify-content-center">
  <div class="grp-menu d-flex flex-column">
    <% if @groups.empty? %>
      <h3>No records found!</h3>
    <% else %>
      <% @groups.each do |group| %>
        <%= link_to group_entities_path(group) do %>
          <div class="grp-item d-flex align-items-center g-20">
            <div class="img-con">
              <% if group.icon.attached? %>
                <img src="<%= (url_for(group.icon))%>", class: "grp-icon", alt="User Image">
              <% end %>
            </div>

            <div class="grp-details d-flex">
              <h3><%= group.name.capitalize %></h3>
            </div>

            <div class="grp-sum d-flex">
              <p>$<%= group.entities.sum(:amount)%></p>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="grp-add">
    <%= link_to "ADD CATEGORY", new_group_path, class:"grp-add-btn" %>
  </div>
</section>

app/views/groups/new.html.erb
<%= render 'partials/newnavgrp' %>

<section class="new-grp d-flex justify-content-center">
<%= render "form", group: @group %>
</section>

app/views/groups/show.htm.erb
<h1>Show Group</h1>

app/views/home/index.html.erb
<section class="home d-flex">
  <div class="text-center">
    <h1 class="home-name fw-bold">Fulus Bank</h1>
    <p class="fw-italic"> Thank you for banking with us</p>
  </div>

  <div class="splash">
    <% if user_signed_in? %>
      <div>
        <%= link_to "CONTINUE", groups_path(current_user), class: 'fw-bold'%>
        <%= button_to "LOGOUT", destroy_user_session_path, method: :delete, class:"btn-bold" %>
      </div>
    <% else %>
      <div class="mb-3 container-sm">
        <%= link_to "LOG IN", new_user_session_path, class: 'white-color form-control btn btn-primary home-btn' %>
      </div>
     
      <div class="container-sm">
        <%= link_to "SIGN UP", new_user_registration_path, class: 'white-color form-control btn btn-primary w100' %>
      </div>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_back.html.erb
<%= link_to root_path do %>
  <i class="fa-solid fa-arrow-left fa-lg nav-back">Back</i>
<% end %>

app/views/partials/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
      <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert]%>
  <div class="alert alert-warning mt-4" role="alert">
    <%=  flash[:alert] %>
  </div>
<%end%>

app/views/partials/_footer.html.erb
<footer class="">
  <h4>Hammed Adisa</h4>
</footer>

app/views/partials/_navgrp.html.erb
<nav class="d-flex nav-grp navbar">
  <%= render "partials/back" %>

  <%= button_to "LOGOUT", destroy_user_session_path, method: :delete, class:"btn-bold" %>
</nav>

app/views/partials/_newent.html.erb
<nav class="d-flex nav-grp align-items-center">
<%= link_to "<Back", group_entities_path, class:"nav-back" %>

  <%= button_to "LOGOUT", destroy_user_session_path, method: :delete, class:"btn-bold" %>
</nav>

app/views/partials/_newnavgrp.html.erb
<nav class="d-flex nav-grp align-items-center">
  <%= link_to "<Back", groups_path, class: "nav-back" %>

  <%= button_to "LOGOUT", destroy_user_session_path, method: :delete, class:"btn-bold" %>
</nav>